/* WCED eLearning TPD Analytics Dashboard - static Supabase client */
const C = window.DASHBOARD_CONFIG || {};
const STATE = {
  supabase:null, connected:false, loading:false, data:{attendance:[],schools:[],sessions:[],courses:[]},
  filteredAttendance:[], view:'overview', charts:{}, sort:{attendance:{key:'Timestamp',dir:'desc'},people:{key:'count',dir:'desc'},schools:{key:'attendance',dir:'desc'},sessions:{key:'session_date',dir:'desc'}},
  pages:{attendance:1,people:1,schools:1,sessions:1}, pageSizes:{attendance:25,people:25,schools:25,sessions:25}, advanced:{hostingDistrict:'',mode:'',facilitator:'',session:'',school:''}, columns:{attendance:['Timestamp','Session Name','Development Level','Facilitator','Hosting District','Delivery Mode','First Name','Surname','District','School']},
  savedViews: JSON.parse(localStorage.getItem('wced_tpd_saved_views')||'[]')
};
const LEVEL_COLORS={'Laying the Foundation':'#8fad15','I can do it':'#ffc600','I can do it better':'#c8126e','The Summit':'#001489','Unknown':'#968c83'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('en-ZA').format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase();
const dateOf=s=>{const d=new Date(s);return isNaN(d)?null:d};
const isoDate=d=>d?d.toISOString().slice(0,10):'';
const monthKey=d=>d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'';
const niceDate=s=>{const d=dateOf(s);return d?d.toLocaleDateString('en-ZA',{year:'numeric',month:'short',day:'numeric'}):String(s||'—')};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2800)}
function setLoading(on,title='Loading dashboard…',detail=''){STATE.loading=on;$('#loading').classList.toggle('hidden',!on);if(on){$('#loadingTitle').textContent=title;$('#loadingDetail').textContent=detail}}
function setConnection(ok,text){STATE.connected=ok;$('#connectionText').textContent=text;const d=document.querySelector('#connectionPill .dot');d.classList.toggle('ok',ok);d.classList.toggle('bad',!ok)}

function makeClient(){const saved=JSON.parse(localStorage.getItem('wced_tpd_supabase_config')||'{}');const url=C.supabaseUrl||saved.url;const key=C.supabaseKey||saved.key;if(!url||!key)return null;return supabase.createClient(url,key,{auth:{persistSession:false}})}

async function fetchAll(table,select,opts={}){
  const pageSize=Math.min(C.pageSize||1000,1000), max=C.maxRowsPerTable||100000; let out=[];
  for(let from=0;from<max;from+=pageSize){
    const to=Math.min(from+pageSize-1,max-1); let q=STATE.supabase.from(table).select(select);
    if(opts.order) q=q.order(opts.order,{ascending:opts.ascending??true});
    const {data,error}=await q.range(from,to); if(error) throw error; out.push(...(data||[]));
    if((data||[]).length<pageSize)break;
    $('#loadingDetail').textContent=`Loaded ${fmt(out.length)} rows from ${table}…`;
  }
  return out;
}

async function loadData(){
  if(!STATE.supabase){setConnection(false,'Add Supabase config');return}
  setLoading(true,'Loading dashboard…','Connecting to Supabase');
  try{
    // Deliberately do not select PERSAL, ID_number, Org_Mail, DataID or Control.
    const [attendance,sessions,courses,schools]=await Promise.all([
      fetchAll('attendance','Timestamp,Session Name,Development Level,Facilitator,Hosting District,Delivery Mode,Surname,First Name,District,School,session_id'),
      fetchAll('sessions','id_key,session_title,hosting_unit,hosting_coordinator,session_date,session_start_time,facilitator,session_delivery_mode,session_link'),
      fetchAll('courses','course_name,developmental_level,integration_level,session_desciption,session_outcomes,programme_duration'),
      fetchAll('schools','EMIS,School_Name,Education_District,Circuit,Quintile,School_Type,Sector')
    ]);
    STATE.data={attendance,sessions,courses,schools};
    setConnection(true,`Connected · ${fmt(attendance.length)} attendance`); populateFilters(); applyFilters(); renderAll();
  }catch(e){console.error(e);setConnection(false,'Connection error');toast(`Supabase error: ${e.message||e}`)}
  finally{setLoading(false)}
}

function populateFilters(){
  const a=STATE.data.attendance;
  const distinct=k=>[...new Set(a.map(r=>r[k]).filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y)));
  const fill=(sel,vals,label)=>{const old=$(sel).value;$(sel).innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.includes(old))$(sel).value=old};
  fill('#districtFilter',distinct('District'),'All districts');fill('#levelFilter',distinct('Development Level'),'All levels');
  buildAdvancedFilters();
}
function buildAdvancedFilters(){
  const a=STATE.data.attendance; const vals=k=>[...new Set(a.map(r=>r[k]).filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y)));
  $('#advancedFilters').innerHTML=`
    <div class="advanced-group"><label>Hosting district</label><select id="advHosting"><option value="">All hosting districts</option>${vals('Hosting District').map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>
    <div class="advanced-group"><label>Delivery mode</label><select id="advMode"><option value="">All delivery modes</option>${vals('Delivery Mode').map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>
    <div class="advanced-group"><label>Facilitator</label><select id="advFac"><option value="">All facilitators</option>${vals('Facilitator').map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>
    <div class="advanced-group"><label>Session contains</label><input id="advSession" placeholder="e.g. AI, Microsoft, webinar"></div>
    <div class="advanced-group"><label>School contains</label><input id="advSchool" placeholder="School name"></div>`;
}
function filters(){return {search:$('#globalSearch').value.trim().toLowerCase(),from:$('#dateFrom').value,to:$('#dateTo').value,district:$('#districtFilter').value,level:$('#levelFilter').value,...STATE.advanced}}
function applyFilters(){
 const f=filters(); STATE.filteredAttendance=STATE.data.attendance.filter(r=>{
   const d=dateOf(r.Timestamp); const ds=d?isoDate(d):''; const blob=[r['Session Name'],r['First Name'],r['Surname'],r.School,r.Facilitator,r.District].join(' ').toLowerCase();
   return (!f.search||blob.includes(f.search))&&(!f.from||!ds||ds>=f.from)&&(!f.to||!ds||ds<=f.to)&&(!f.district||r.District===f.district)&&(!f.level||r['Development Level']===f.level)&&(!f.hostingDistrict||r['Hosting District']===f.hostingDistrict)&&(!f.mode||r['Delivery Mode']===f.mode)&&(!f.facilitator||r.Facilitator===f.facilitator)&&(!f.session||norm(r['Session Name']).includes(norm(f.session)))&&(!f.school||norm(r.School).includes(norm(f.school)));
 });
 STATE.pages={attendance:1,people:1,schools:1,sessions:1}; updateFilterChips(); renderAll();
}
function updateFilterChips(){
 const f=filters(); const bits=[]; if(f.search)bits.push(`Search: ${f.search}`);if(f.from||f.to)bits.push(`Date: ${f.from||'…'} → ${f.to||'…'}`);if(f.district)bits.push(`District: ${f.district}`);if(f.level)bits.push(`Level: ${f.level}`);if(f.hostingDistrict)bits.push(`Host: ${f.hostingDistrict}`);if(f.mode)bits.push(`Mode: ${f.mode}`);if(f.facilitator)bits.push(`Facilitator: ${f.facilitator}`);
 $('#attendanceFilters').innerHTML=(bits.length?bits:['No advanced filters active']).map(x=>`<span class="filter-chip">${esc(x)}</span>`).join('');
 $('#overviewSubtitle').textContent=STATE.connected?`${fmt(STATE.filteredAttendance.length)} attendance records match the current filters.`:'Connect Supabase to populate the dashboard.';
}

function participantMap(rows){const m=new Map();rows.forEach(r=>{const key=`${norm(r['First Name'])}|${norm(r.Surname)}|${norm(r.School)}`; if(!key.replace(/\|/g,''))return;let o=m.get(key);if(!o)o={key,name:[r['First Name'],r.Surname].filter(Boolean).join(' '),school:r.School||'Unknown',district:r.District||'Unknown',count:0,sessions:new Set(),levels:new Set(),last:null};o.count++;if(r['Session Name'])o.sessions.add(r['Session Name']);if(r['Development Level'])o.levels.add(r['Development Level']);if(r.Timestamp&&!o.last||dateOf(r.Timestamp)>dateOf(o.last))o.last=r.Timestamp;m.set(key,o)});return [...m.values()].map(o=>({...o,sessions:o.sessions.size,levels:[...o.levels].join(', ')}))}
function schoolMap(rows){const m=new Map();rows.forEach(r=>{const key=norm(r.School)||'unknown';let o=m.get(key);if(!o)o={school:r.School||'Unknown',district:r.District||'Unknown',attendance:0,people:new Set(),sessions:new Set(),last:null};o.attendance++;o.people.add(`${norm(r['First Name'])}|${norm(r.Surname)}`);if(r['Session Name'])o.sessions.add(r['Session Name']);if(r.Timestamp&&!o.last||dateOf(r.Timestamp)>dateOf(o.last))o.last=r.Timestamp;m.set(key,o)});return [...m.values()].map(o=>({...o,people:o.people.size,sessions:o.sessions.size}))}

function destroyCharts(){Object.values(STATE.charts).forEach(c=>{try{c.destroy()}catch{}});STATE.charts={}}
function chart(id,type,labels,data,opts={}){const el=document.getElementById(id);if(!el||typeof Chart==='undefined')return;STATE.charts[id]=new Chart(el.getContext('2d'),{type,data:{labels,datasets:[{label:opts.label||'',data,backgroundColor:opts.colors||'#001489',borderColor:opts.border||'#001489',borderWidth:2,tension:.28,fill:type==='line'&&!!opts.fill}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:!!opts.legend}},scales:type==='doughnut'?{}:{y:{beginAtZero:true,grid:{color:'rgba(120,130,145,.12)' }},x:{grid:{display:false}}}}})}
function renderOverview(){
 const a=STATE.filteredAttendance, p=participantMap(a), schools=schoolMap(a); const sessions=[...new Set(a.map(r=>r['Session Name']).filter(Boolean))]; const courses=STATE.data.courses.length;
 const k=[['Attendance records',fmt(a.length),'Filtered records'],['Unique participants',fmt(p.length),'Name + school estimate'],['Schools reached',fmt(schools.length),'Within current filters'],['Sessions',fmt(sessions.length),'Unique session names'],['Courses',fmt(courses),'Catalogue records'],['Avg records / session',sessions.length? (a.length/sessions.length).toFixed(1):'0.0','Attendance intensity']];
 $('#kpis').innerHTML=k.map(x=>`<div class="kpi"><div class="label">${esc(x[0])}</div><div class="value">${x[1]}</div><div class="note">${esc(x[2])}</div></div>`).join('');
 destroyCharts();
 const trend={};a.forEach(r=>{const d=dateOf(r.Timestamp);const k=$('#trendGranularity').value==='week'&&d?`${d.getFullYear()}-W${String(Math.ceil((((d-new Date(d.getFullYear(),0,1))/86400000)+1)/7)).padStart(2,'0')}`:monthKey(d);if(k)trend[k]=(trend[k]||0)+1});const tkeys=Object.keys(trend).sort();chart('trendChart','line',tkeys,tkeys.map(k=>trend[k]),{label:'Attendance'});
 const dm={};a.forEach(r=>{const k=r.District||'Unknown';dm[k]=(dm[k]||0)+1});const dks=Object.entries(dm).sort((x,y)=>y[1]-x[1]).slice(0,12);chart('districtChart','bar',dks.map(x=>x[0]),dks.map(x=>x[1]),{label:'Attendance',colors:'#007dba'});
 const lm={};a.forEach(r=>{const k=r['Development Level']||'Unknown';lm[k]=(lm[k]||0)+1});const lks=Object.entries(lm).sort((x,y)=>y[1]-x[1]);chart('levelChart','doughnut',lks.map(x=>x[0]),lks.map(x=>x[1]),{colors:lks.map(x=>LEVEL_COLORS[x[0]]||'#968c83'),legend:true});
 const mm={};a.forEach(r=>{const k=r['Delivery Mode']||'Unknown';mm[k]=(mm[k]||0)+1});const mks=Object.entries(mm).sort((x,y)=>y[1]-x[1]);chart('modeChart','doughnut',mks.map(x=>x[0]),mks.map(x=>x[1]),{colors:['#001489','#00a1a3','#ffc600','#c8126e','#587f95','#8fad15'],legend:true});
 const topS={};a.forEach(r=>{const k=r['Session Name']||'Unknown';topS[k]=(topS[k]||0)+1});renderRank('#topSessions',Object.entries(topS).sort((x,y)=>y[1]-x[1]).slice(0,7));renderRank('#topSchools',schools.sort((x,y)=>y.attendance-x.attendance).slice(0,8).map(x=>[x.school,x.attendance]));
 const rs=[...STATE.data.sessions].sort((a,b)=>String(b.session_date||'').localeCompare(String(a.session_date||''))).slice(0,7);$('#recentSessions').innerHTML=rs.length?rs.map(s=>`<div class="row"><div>${esc(s.session_title)}<div class="muted">${niceDate(s.session_date)} · ${esc(s.session_delivery_mode||'')}</div></div><div class="value">${fmt(a.filter(r=>r.session_id===s.id_key||r['Session Name']===s.session_title).length)}</div></div>`).join(''):`<div class="muted">No sessions</div>`;
}
function renderRank(sel,rows){$(sel).innerHTML=rows.length?rows.map((r,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div class="rank-name" title="${esc(r[0])}">${esc(r[0])}</div><div class="rank-value">${fmt(r[1])}</div></div>`).join(''):`<div class="muted">No data</div>`}

function renderAttendance(){const a=STATE.filteredAttendance;const cols=STATE.columns.attendance;const sorted=[...a].sort((x,y)=>cmp(x,y,STATE.sort.attendance.key,STATE.sort.attendance.dir));$('#attendanceCount').textContent=`${fmt(a.length)} records`;$('#attendanceTable').innerHTML=`<thead><tr>${cols.map(c=>`<th data-sort-att="${esc(c)}">${esc(c)}</th>`).join('')}<th>Open</th></tr></thead><tbody>${page(sorted,'attendance').map((r,idx)=>`<tr>${cols.map(c=>`<td>${c==='Timestamp'?niceDate(r[c]):esc(r[c]||'—')}</td>`).join('')}<td><button class="text-btn" data-row-att="${a.indexOf(r)}">View</button></td></tr>`).join('')}</tbody>`;renderPager('attendancePager',sorted.length,'attendance');}
function renderPeople(){const rows=participantMap(STATE.filteredAttendance);const q=$('#peopleSearch').value.trim().toLowerCase();const filtered=rows.filter(r=>`${r.name} ${r.school} ${r.district}`.toLowerCase().includes(q));const active=[...rows].sort((a,b)=>b.count-a.count);$('#peopleKpis').innerHTML=[['Participants',rows.length,'Estimated unique'],['Repeat participants',rows.filter(x=>x.count>1).length,'2+ attendance records'],['Avg attendances',rows.length?(rows.reduce((s,x)=>s+x.count,0)/rows.length).toFixed(1):'0','Per participant'],['Max attendances',rows[0]?Math.max(...rows.map(x=>x.count)):0,'Highest individual total']].map(x=>`<div class="kpi"><div class="label">${esc(x[0])}</div><div class="value">${fmt(x[1])}</div><div class="note">${esc(x[2])}</div></div>`).join('');const repeat={};rows.forEach(x=>repeat[x.count]=(repeat[x.count]||0)+1);chart('repeatChart','bar',Object.keys(repeat).sort((a,b)=>a-b),Object.keys(repeat).sort((a,b)=>a-b).map(k=>repeat[k]),{label:'People',colors:'#00a1a3'});renderRank('#activePeople',active.slice(0,8).map(x=>[`${x.name||'Unknown'} · ${x.school||'Unknown'}`,x.count]));$('#peopleCount').textContent=`${fmt(filtered.length)} participants`;const sort=filtered.sort((a,b)=>cmp(a,b,STATE.sort.people.key,STATE.sort.people.dir));$('#peopleTable').innerHTML=`<thead><tr><th>Participant</th><th>School</th><th>District</th><th>Attendances</th><th>Sessions</th><th>Last attendance</th><th>Levels</th></tr></thead><tbody>${page(sort,'people').map(r=>`<tr><td>${esc(r.name||'Unknown')}</td><td>${esc(r.school||'Unknown')}</td><td>${esc(r.district||'Unknown')}</td><td>${fmt(r.count)}</td><td>${fmt(r.sessions)}</td><td>${niceDate(r.last)}</td><td>${esc(r.levels||'—')}</td></tr>`).join('')}</tbody>`;renderPager('peoplePager',sort.length,'people')}
function renderSchools(){const rows=schoolMap(STATE.filteredAttendance);const q=$('#schoolsSearch').value.trim().toLowerCase();const filtered=rows.filter(r=>`${r.school} ${r.district}`.toLowerCase().includes(q));$('#schoolsCount').textContent=`${fmt(filtered.length)} schools`;const top=filtered.sort((a,b)=>b.attendance-a.attendance);chart('schoolChart','bar',top.slice(0,15).map(x=>x.school),top.slice(0,15).map(x=>x.attendance),{label:'Attendance',colors:'#8fad15'});const meta=new Map(STATE.data.schools.map(s=>[norm(s.School_Name),s]));const totals={primary:0,secondary:0};STATE.data.schools.forEach(s=>{if(norm(s.School_Type).includes('primary'))totals.primary++;if(norm(s.School_Type).includes('secondary'))totals.secondary++});$('#schoolSummary').innerHTML=[['Schools in source',STATE.data.schools.length],['Schools in filtered attendance',rows.length],['Primary schools in source',totals.primary],['Secondary schools in source',totals.secondary]].map(x=>`<div class="school-stat"><span>${esc(x[0])}</span><strong>${fmt(x[1])}</strong></div>`).join('');const s=top;$('#schoolsTable').innerHTML=`<thead><tr><th>School</th><th>District</th><th>Attendance</th><th>Participants</th><th>Sessions</th><th>Last attendance</th><th>School type</th><th>Quintile</th><th>Sector</th></tr></thead><tbody>${page(s,'schools').map(r=>{const m=meta.get(norm(r.school))||{};return `<tr><td>${esc(r.school)}</td><td>${esc(r.district)}</td><td>${fmt(r.attendance)}</td><td>${fmt(r.people)}</td><td>${fmt(r.sessions)}</td><td>${niceDate(r.last)}</td><td>${esc(m.School_Type||'—')}</td><td>${esc(m.Quintile||'—')}</td><td>${esc(m.Sector||'—')}</td></tr>`}).join('')}</tbody>`;renderPager('schoolsPager',s.length,'schools')}
function renderSessions(){const a=STATE.filteredAttendance;const rows=STATE.data.sessions.filter(s=>{const search=$('#sessionsSearch').value.trim().toLowerCase();return !search||[s.session_title,s.facilitator,s.hosting_unit,s.hosting_coordinator].join(' ').toLowerCase().includes(search)}).map(s=>({...s,attendance:a.filter(r=>r.session_id===s.id_key||r['Session Name']===s.session_title).length}));$('#sessionsCount').textContent=`${fmt(rows.length)} sessions`;const byM={};rows.forEach(s=>{if(s.session_date){const k=monthKey(dateOf(s.session_date));byM[k]=(byM[k]||0)+1}});const ks=Object.keys(byM).sort();chart('sessionTrendChart','line',ks,ks.map(k=>byM[k]),{label:'Sessions',colors:'#c8126e'});const f={};rows.forEach(s=>{const k=s.facilitator||'Unknown';f[k]=(f[k]||0)+1});const fk=Object.entries(f).sort((x,y)=>y[1]-x[1]).slice(0,12);chart('facilitatorChart','bar',fk.map(x=>x[0]),fk.map(x=>x[1]),{label:'Sessions',colors:'#587f95'});const sorted=rows.sort((a,b)=>cmp(a,b,STATE.sort.sessions.key,STATE.sort.sessions.dir));$('#sessionsTable').innerHTML=`<thead><tr><th>Date</th><th>Session</th><th>Hosting unit</th><th>Coordinator</th><th>Facilitator</th><th>Mode</th><th>Attendance</th><th>Link</th></tr></thead><tbody>${page(sorted,'sessions').map(s=>`<tr><td>${niceDate(s.session_date)}</td><td>${esc(s.session_title)}</td><td>${esc(s.hosting_unit||'—')}</td><td>${esc(s.hosting_coordinator||'—')}</td><td>${esc(s.facilitator||'—')}</td><td><span class="badge">${esc(s.session_delivery_mode||'—')}</span></td><td>${fmt(s.attendance)}</td><td>${s.session_link?`<a href="${esc(s.session_link)}" target="_blank" rel="noopener" class="text-btn">Open</a>`:'—'}</td></tr>`).join('')}</tbody>`;renderPager('sessionsPager',sorted.length,'sessions');}
function renderCourses(){const c=STATE.data.courses;$('#courseGrid').innerHTML=c.length?c.map(x=>`<article class="course-card"><div class="course-tag">${esc(x.developmental_level||'Unclassified')}</div><h3>${esc(x.course_name)}</h3><p>${esc(x.session_desciption||'No description provided.')}</p><div class="course-meta"><span>${esc(x.integration_level||'')}</span><strong>${x.programme_duration?esc(x.programme_duration)+' min':'Duration N/A'}</strong></div></article>`).join(''):`<div class="card"><div class="muted">No courses found.</div></div>`}
function renderAll(){updateFilterChips();renderOverview();renderAttendance();renderPeople();renderSchools();renderSessions();renderCourses()}
function cmp(a,b,key,dir){let x=a[key],y=b[key];if(key==='count'||key==='attendance'||key==='sessions'){} x=String(x??'').toLowerCase();y=String(y??'').toLowerCase();const xn=Number(x),yn=Number(y);let r=(!isNaN(xn)&&!isNaN(yn)&&x!==''&&y!=='')?xn-yn:x.localeCompare(y);return dir==='desc'?-r:r}
function page(arr,type){const size=STATE.pageSizes[type];const start=(STATE.pages[type]-1)*size;return arr.slice(start,start+size)}
function renderPager(id,total,type){const size=STATE.pageSizes[type], pages=Math.max(1,Math.ceil(total/size)),p=Math.min(STATE.pages[type],pages);STATE.pages[type]=p;const buttons=[];for(let i=1;i<=pages;i++){if(pages<=8||Math.abs(i-p)<=2||i===1||i===pages)buttons.push(`<button class="${i===p?'active':''}" data-page="${type}:${i}">${i}</button>`);else if(buttons[buttons.length-1]!=='…')buttons.push('…')}$( '#'+id).innerHTML=`<button data-page="${type}:${Math.max(1,p-1)}">‹</button>${buttons.map(b=>b==='…'?`<span>…</span>`:b).join('')}<button data-page="${type}:${Math.min(pages,p+1)}">›</button>`}

function showModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function attendanceDetail(r){const fields=['Timestamp','Session Name','Development Level','Facilitator','Hosting District','Delivery Mode','First Name','Surname','District','School','session_id'];showModal('Attendance record',`<div class="detail-grid">${fields.map(k=>`<div class="detail-item"><div class="k">${esc(k)}</div><div class="v">${k==='Timestamp'?niceDate(r[k]):esc(r[k]||'—')}</div></div>`).join('')}</div>`)}
function openView(v){STATE.view=v;$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active-view'));$('#view-'+v).classList.add('active-view');const titles={overview:'Programme Overview',attendance:'Attendance Explorer',people:'Participant Analysis',schools:'School Engagement',sessions:'Session Intelligence',courses:'Course Catalogue'};$('#pageTitle').textContent=titles[v];if(v==='overview')renderOverview();if(window.innerWidth<901)$('#sidebar').classList.remove('open')}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function download(name,content,type='text/csv'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportRows(rows,name){if(!rows.length){toast('Nothing to export');return}const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))];const csv=[headers.map(csvEscape).join(','),...rows.map(r=>headers.map(h=>csvEscape(typeof r[h]==='object'?JSON.stringify(r[h]):r[h])).join(','))].join('\n');download(name,csv)}
function exportCurrent(){exportRows(STATE.filteredAttendance.map(r=>{const x={...r};delete x['PERSAL Number'];delete x.ID_number;return x;}),'attendance-export.csv')}
function printReport(){window.print()}
function saveView(){const name=prompt('Name this saved view');if(!name)return;const view={name,filters:{...filters()},created:new Date().toISOString()};STATE.savedViews.push(view);localStorage.setItem('wced_tpd_saved_views',JSON.stringify(STATE.savedViews));toast('Saved view created')}
function showSavedViews(){showModal('Saved views',STATE.savedViews.length?STATE.savedViews.map((v,i)=>`<div class="detail-item" style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;gap:8px"><strong>${esc(v.name)}</strong><button class="text-btn" data-load-view="${i}">Load</button></div><div class="muted" style="margin-top:6px">${esc(JSON.stringify(v.filters))}</div></div>`).join(''):`<div class="muted">No saved views yet. Use Advanced filters → Save view.</div>`)}
function loadSaved(i){const v=STATE.savedViews[i];if(!v)return;const f=v.filters||{};$('#globalSearch').value=f.search||'';$('#dateFrom').value=f.from||'';$('#dateTo').value=f.to||'';$('#districtFilter').value=f.district||'';$('#levelFilter').value=f.level||'';STATE.advanced={hostingDistrict:f.hostingDistrict||'',mode:f.mode||'',facilitator:f.facilitator||'',session:f.session||'',school:f.school||''};applyFilters();$('#modal').classList.add('hidden');toast(`Loaded ${v.name}`)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('wced_tpd_theme',document.body.classList.contains('dark')?'dark':'light');if(STATE.view==='overview')renderOverview()}

// Events
$('#refreshBtn').addEventListener('click',loadData);$('#themeBtn').addEventListener('click',toggleTheme);$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#filterBtn').addEventListener('click',applyFilters);$('#clearFiltersBtn').addEventListener('click',()=>{['globalSearch','dateFrom','dateTo'].forEach(id=>$('#'+id).value='');$('#districtFilter').value='';$('#levelFilter').value='';STATE.advanced={hostingDistrict:'',mode:'',facilitator:'',session:'',school:''};applyFilters()});$('#globalSearch').addEventListener('input',()=>{clearTimeout(window.searchTimer);window.searchTimer=setTimeout(applyFilters,250)});$('#trendGranularity').addEventListener('change',renderOverview);$('#attendancePageSize').addEventListener('change',e=>{STATE.pageSizes.attendance=+e.target.value;STATE.pages.attendance=1;renderAttendance()});$('#peopleSearch').addEventListener('input',renderPeople);$('#schoolsSearch').addEventListener('input',renderSchools);$('#sessionsSearch').addEventListener('input',renderSessions);
document.addEventListener('click',e=>{
 const nav=e.target.closest('[data-view]');if(nav)return openView(nav.dataset.view);
 const act=e.target.closest('[data-action]');if(act){const a=act.dataset.action;if(a==='filters')$('#filterDrawer').classList.remove('hidden');if(a==='settings')showConfigModal();if(a==='export'||a==='exportPeople'||a==='exportSchools'||a==='exportSessions'||a==='exportCourses')doExport(a);if(a==='print')printReport();if(a==='savedViews')showSavedViews();if(a==='columnPicker')showColumnPicker();if(a==='saveView')saveView();if(a==='applyAdvancedFilters'){STATE.advanced={hostingDistrict:$('#advHosting').value,mode:$('#advMode').value,facilitator:$('#advFac').value,session:$('#advSession').value,school:$('#advSchool').value};$('#filterDrawer').classList.add('hidden');applyFilters()}}
 const close=e.target.closest('[data-close-modal]');if(close)$('#modal').classList.add('hidden');const cd=e.target.closest('[data-close-drawer]');if(cd)$('#filterDrawer').classList.add('hidden');
 const pageBtn=e.target.closest('[data-page]');if(pageBtn){const [type,p]=pageBtn.dataset.page.split(':');STATE.pages[type]=+p;({attendance:renderAttendance,people:renderPeople,schools:renderSchools,sessions:renderSessions}[type])()}
 const sh=e.target.closest('[data-row-att]');if(sh){const r=STATE.filteredAttendance[+sh.dataset.rowAtt];attendanceDetail(r)}
 const th=e.target.closest('[data-sort-att]');if(th){const k=th.dataset.sortAtt;const s=STATE.sort.attendance;if(s.key===k)s.dir=s.dir==='asc'?'desc':'asc';else{s.key=k;s.dir='asc'}renderAttendance()}
 const link=e.target.closest('[data-view-link]');if(link)openView(link.dataset.viewLink);
 const drill=e.target.closest('[data-drill]');if(drill){openView('attendance');toast('Attendance explorer opened — use the district filter for a detailed view')}
 const saveCfg=e.target.closest('#saveConfig');if(saveCfg){const url=$('#cfgUrl').value.trim(),key=$('#cfgKey').value.trim();if(!url||!key){toast('Enter both Supabase values');return}localStorage.setItem('wced_tpd_supabase_config',JSON.stringify({url,key}));STATE.supabase=makeClient();$('#modal').classList.add('hidden');loadData()}

 const lv=e.target.closest('[data-load-view]');if(lv)loadSaved(+lv.dataset.loadView);
});
function doExport(a){if(a==='export')return exportCurrent();if(a==='exportPeople')return exportRows(participantMap(STATE.filteredAttendance),'people-export.csv');if(a==='exportSchools')return exportRows(schoolMap(STATE.filteredAttendance),'schools-export.csv');if(a==='exportSessions')return exportRows(STATE.data.sessions.map(s=>({...s,attendance:STATE.filteredAttendance.filter(r=>r.session_id===s.id_key||r['Session Name']===s.session_title).length})),'sessions-export.csv');if(a==='exportCourses')return exportRows(STATE.data.courses,'courses-export.csv')}
function showConfigModal(){const saved=JSON.parse(localStorage.getItem('wced_tpd_supabase_config')||'{}');showModal('Supabase configuration',`<p class="muted">Use your Supabase Project URL and browser-safe publishable/anon key.</p><div class="advanced-group"><label>Project URL</label><input id="cfgUrl" value="${esc(C.supabaseUrl||saved.url||'')}" placeholder="https://xxxxx.supabase.co"></div><div class="advanced-group"><label>Publishable / anon key</label><input id="cfgKey" type="password" value="${esc(C.supabaseKey||saved.key||'')}" placeholder="eyJhbGci…"></div><div class="detail-item"><div class="k">Security</div><div class="v">Never use a service_role or secret key in browser code. Supabase RLS must control what this dashboard can read.</div></div><div style="margin-top:14px"><button class="btn primary" id="saveConfig">Connect and save locally</button></div>`)}
function showColumnPicker(){const fields=['Timestamp','Session Name','Development Level','Facilitator','Hosting District','Delivery Mode','First Name','Surname','District','School'];showModal('Attendance columns',fields.map(f=>`<label style="display:block;padding:7px 0"><input type="checkbox" data-col="${esc(f)}" ${STATE.columns.attendance.includes(f)?'checked':''}> ${esc(f)}</label>`).join('')+`<div style="margin-top:12px"><button class="btn primary" id="saveColumns">Apply</button></div>`);$('#saveColumns').addEventListener('click',()=>{STATE.columns.attendance=fields.filter(f=>$('#modalBody input[data-col="'+CSS.escape(f)+'"]')?.checked);if(!STATE.columns.attendance.length)STATE.columns.attendance=['Timestamp','Session Name'];$('#modal').classList.add('hidden');renderAttendance()})}

if(localStorage.getItem('wced_tpd_theme')==='dark')document.body.classList.add('dark');
STATE.supabase=makeClient();
if(!STATE.supabase){setConnection(false,'Add Supabase config');toast('Add your Supabase URL and publishable key to config.js, then refresh.')}else loadData();
